@baseUrl = http://localhost:8080

#
GET {{baseUrl}}/ping
###

#
GET {{baseUrl}}/volumes
###

#
GET {{baseUrl}}/volumes/volume
###

#
GET {{baseUrl}}/volumes/volume/snapshot
###

#
POST  {{baseUrl}}/volumes
###

#
POST  {{baseUrl}}/volumes/volume
###

#
POST  {{baseUrl}}/volumes/volume/snapshot
###