# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: [ "main" , "dev" ]
  pull_request:
    branches: [ "main" ]
    paths-ignore:
      - "**/*.md"

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: "1.20"
    - run: go version

    - name: Vet
      run: |
        go vet ./...
    
    - name: Unit tests
      run: go test -v ./... -coverprofile=coverage.out -covermode=count
    - name: fix coverage.out paths (_/home... -> ./)
      run: |
        cat coverage.out
        sed -i "s#_$(pwd)#.#g" coverage.out
        cat coverage.out
    - name: publish Go test results coverage
      uses: actions/upload-artifact@v2
      with:
        name: code covarege report
        path: coverage.out

    # https://medium.com/synechron/how-to-set-up-a-test-coverage-threshold-in-go-and-github-167f69b940dc
    - name: Quality Gate - Test coverage shall be above threshold
      env:
          TESTCOVERAGE_THRESHOLD: 0
      run: |
            echo "Quality Gate: checking test coverage is above threshold ..."
            echo "Threshold             : $TESTCOVERAGE_THRESHOLD %"
            totalCoverage=`go tool cover -func=coverage.out | grep total | grep -Eo '[0-9]+\.[0-9]+'`
            echo "Current test coverage : $totalCoverage %"
            if (( $(echo "$totalCoverage $TESTCOVERAGE_THRESHOLD" | awk '{print ($1 >= $2)}') )); then
                echo "OK"
            else
                echo "Current test coverage is below threshold. Please add more unit tests or adjust threshold to a lower value."
                echo "Failed"
                exit 1
            fi
